run:
  run_id: dataloader_norm_test
  artifacts_root: artifacts/runs

dataloader:
  real_dir: artifacts/datasets/rawdatasets
  image_dir: artifacts/datasets/rawdatasets/images
  label_dir: artifacts/datasets/rawdatasets/labels
  label_ext: .txt
  require_labels: true
  patterns:
    - "*.png"
    - "*.jpg"
    - "*.jpeg"

  output:
    root_dir: artifacts/datasets/normalized/${services_id}_${task_name}
    images_subdir: images
    labels_subdir: labels

  naming:
    canonicalize_names: true
    services_id: yk-001 # proving that data original from same services
    task_name: arm_deltoid_muscle_seg # task relevant is aligning with our design target which aim "task" as start
    filename_template: ${services_id}_${task_name}_${seq_id_padded} # normlizing file name template
    id_width: 4
    id_start: 1
    target_image_ext: .png
    materialize_mode: copy
