run:
  run_id: dataloader_norm_test_generation_yk001
  artifacts_root: artifacts/runs

dataloader:
  real_dir: test/test-generation/yk-001_arm_deltoid_muscle_seg
  image_dir: test/test-generation/yk-001_arm_deltoid_muscle_seg/images
  label_ext: .txt
  require_labels: false
  patterns:
    - "*.png"
    - "*.jpg"
    - "*.jpeg"

  naming:
    canonicalize_names: false
    services_id: yk-001
    task_name: arm_deltoid_muscle_seg
