filter_input_configs:
  input_manifests:  # generation 的产出，可以多批次的任务
    - artifacts/runs/yk003/body_pose_coco/body_pose_coco__prompt/generate/synth_manifest.jsonl
    - artifacts/runs/yk003/body_pose_coco/body_pose_coco__prompt_canny/generate/synth_manifest.jsonl
  # 可能上面用到了source image 作为 guided 生成，例如我们的body_pose_coco__prompt_canny任务就用到了，那么可以通过这个产出文件找到对应的 guided image 的真实地址
  anchor_real_manifest: artifacts/runs/yk003/body_pose_coco/body_pose_coco_norm/dataloader/real_manifest.jsonl

output: configs/coco_pose_2017__expansion/filter/artifacts/tmp/body_pose_coco_siglip2_input_manifest.jsonl