"""add meta to collection_runs

Revision ID: 966b430168b8
Revises: c166bf45719e
Create Date: 2025-11-30 18:17:46.268656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '966b430168b8'
down_revision: Union[str, Sequence[str], None] = 'c166bf45719e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_runs', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_runs', 'meta')
    # ### end Alembic commands ###
