services:
  comfyui:
    build:
      context: ..
      dockerfile: ComfyUI/Dockerfile
    container_name: comfyui-service
    restart: unless-stopped

    # 把 GPU 需求写在这里
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]

    environment:
      - COMFYUI_PORT=8188
      - COMFYUI_EXTRA_ARGS=--disable-auto-launch

    ports:
      - "8188:8188"

    volumes:
      - ../data/comfyui/models:/app/models
      - ../data/comfyui/output:/app/output
      - ../data/comfyui/custom_nodes:/app/custom_nodes
